# Generated by Django 5.1.1 on 2024-09-10 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='reserved_time',
        ),
        migrations.AddField(
            model_name='availabletime',
            name='reserved_time',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.availabletime'),
        ),
    ]
