# Generated by Django 5.1.1 on 2024-09-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_patient_reserved_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='reserved_time',
        ),
        migrations.AddField(
            model_name='availabletime',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
