# Generated by Django 5.1.1 on 2024-09-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_availabletime_reserved_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='specializations',
        ),
    ]
