# Generated by Django 5.1.1 on 2024-09-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_comment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.patient'),
        ),
    ]
