# Generated by Django 5.1.1 on 2024-09-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_doctor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='biography',
            field=models.TextField(verbose_name='درباره دکتر'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_address',
            field=models.TextField(verbose_name='آدرس مطب'),
        ),
    ]
