# Generated by Django 5.1.1 on 2024-09-10 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_doctor_biography_alter_doctor_clinic_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specializations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.specialization', verbose_name='تخصص'),
        ),
    ]
