# Generated by Django 5.1.1 on 2024-09-10 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_doctor_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='deleted_at',
        ),
    ]
