# Generated by Django 5.1.1 on 2024-09-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
