# Generated by Django 5.1.1 on 2024-09-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_availabletime_options_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specializations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.specialization', verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
