# Generated by Django 4.2.5 on 2024-09-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_availabletime_options_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.IntegerField(unique=True, verbose_name='کد نظام پزشکی'),
        ),
    ]
