# Generated by Django 5.1.1 on 2024-09-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_comment_id_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
