# Generated by Django 5.1.1 on 2024-09-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_availabletime_options_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='empty.jpg', null=True, upload_to='%Y-%m-%d', verbose_name='بارگذاری تصویر'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.IntegerField(unique=True, verbose_name='کد نظام پزشکی'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='ایجاد تخصص جدید'),
        ),
    ]
