# Generated by Django 5.1.1 on 2024-09-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_comment_id_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
    ]
