# Generated by Django 5.1.1 on 2024-09-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_doctor_image_alter_doctor_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='visit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
