# Generated by Django 5.1.1 on 2024-09-13 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_rename_id_deleted_comment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='management.comment'),
        ),
        migrations.AddField(
            model_name='rating',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.doctor'),
        ),
    ]
