# Generated by Django 5.1.1 on 2024-09-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_rating_comment_rating_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
    ]
