# Generated by Django 5.1.1 on 2024-09-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_remove_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.comment'),
        ),
    ]
